### PR TITLE
Add initial personas doc

### PR DESCRIPTION
**Pull request by jdolitsky**
As discussed in today's meeting, putting these into the repo!

### CODE REVIEW

**Comment by SteveLasker** [comment]
For the personas, should we capture the interop registry operators? Is there a "big company that buys new trucks" persona, vs. the small company that "keeps their old trucks" personas?

This way we can think through compat experiences.

**Comment by nishakm** [comment]
We can add more personas in the future, right?

**Comment by jdolitsky** [comment]
I think for each persona listed, it is implied that each of them comes in varying degrees of quality, for example:
- a fancy factory with the latest tech vs. a rundown one
- a super strict health inspector vs. a lax one

I don't think more personas are necessary because this "real-life" scenario already takes into account life's imperfections and intricacies.

That being said, the truck/truck driver is a big focal point of what we're designing here.

To Nisha's point we can built atop this later on, and would be nice to just get something in :)

**Comment by SteveLasker** [comment]
While I agree with the points, the biggest tension we've had is around "new trucks" with anti-lock brakes, lane control, internet connectivity for maps and locations, and "older trucks" that haven't been upgraded, that you might plug something into the cigarette lighter, but the "experience" is far less.

What I'm suggesting is we capture the need round trip a reference type between an old truck and a new truck. We shouldn't have data-loss. The experience may not be as good, but we don't want to lose granularity in the contents.

**Comment by jdolitsky** [comment]
I still think it's all implied... you're getting into the weeds on what is meant to be essentially a childrens' book version of the WG.

**Comment by nishakm** [comment]
@SteveLasker I feel like the use case you are trying to capture may fall under "logistics". I think a logistician would still need to interact with farmers, truck drivers, etc. Therefore, it may add a layer of complexity which isn't the goal. Think about it this way: if one person did the farming, the making of the ice cream, the shipping, and the inspecting, that's a whole lot of work!

That said, if there was a persona like a "truck supplier", I think there is room to add something like that in the future.

**Comment by SteveLasker** [comment]
I leave it to you and Josh to creativley map the abstraction to ice cream delivery. 
Im just trying to capture interop and round tripping of reference types. I’d suggest no data loss is the requirement, while the experience may be different on registries that don’t support the query and lifecycle capabilities, while others do adopt these new outcomes.

**Comment by jdolitsky** [comment]
> I leave it to you and Josh to creativley map the abstraction to ice cream delivery.

Ok, then with Nisha and I in agreement, it sounds like we are good to merge this in.

cc @lachie83 @justincormack @michaelb990 @dmcgowan @jonjohnsonjr

**Comment by jdolitsky** [comment]
Removed the jpegs and replaced with emojis to avoid lawyer stuffs

**Review by jonjohnsonjr — APPROVED** [review]

**Comment by dlorenc** [comment]
Nice!

**Pull request merged**
